FROM datacharmer/mysql-sb-base

MAINTAINER Giuseppe Maxia <gmax@cpan.org>

COPY dbdata /opt/mysql

USER msandbox
WORKDIR /home/msandbox
ENV USER=msandbox

COPY README.md /home/msandbox/README

COPY docker-entrypoint.sh /
ENTRYPOINT [ "/docker-entrypoint.sh" ]
 
