FROM datacharmer/mysql-sb-base

LABEL MAINTAINER Giuseppe Maxia <gmax@cpan.org>

COPY dbdata-gz /opt/mysql
COPY setup.sh /home/msandbox/setup.sh

USER msandbox
WORKDIR /home/msandbox
ENV USER=msandbox

COPY README.md /home/msandbox/README

COPY docker-entrypoint.sh /
ENTRYPOINT [ "/docker-entrypoint.sh" ]

